apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
  labels:
    app: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app-deployment
        image: sumedhpatkar/scratch-app-2:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-app-deployment
spec:
  type: NodePort
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
